[package]
name = "cennznet-runtime"
version = "1.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
build = "build.rs"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
rustc-hex = { version = "2.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
serde = { version = "1.0.101", optional = true }
cennzx-spot = { package = "crml-cennzx-spot", path = "../crml/cennzx-spot", default-features = false }

authority-discovery-primitives = { package = "substrate-authority-discovery-primitives", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
client = { package = "substrate-client", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
cennznet-primitives = { path = "../primitives", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
primitives = { package = "substrate-primitives",  git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
rstd = { package = "sr-std", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
sr-primitives = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
sr-staking-primitives = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
substrate-keyring = { git = "https://github.com/plugblockchain/plug-blockchain", optional = true, branch = "chore/add-generic-asset-reward-method" }
substrate-session = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
version = { package = "sr-version", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }

authority-discovery = { package = "srml-authority-discovery", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
authorship = { package = "srml-authorship", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
attestation = { package = "prml-attestation", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
babe = { package = "srml-babe", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
collective = { package = "srml-collective", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
contracts = { package = "srml-contracts", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
contracts-rpc-runtime-api = { package = "srml-contracts-rpc-runtime-api", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
democracy = { package = "srml-democracy", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
elections-phragmen = { package = "srml-elections-phragmen", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
executive = { package = "srml-executive", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
finality-tracker = { package = "srml-finality-tracker", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
generic-asset = { package = "srml-generic-asset", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
grandpa = { package = "srml-grandpa", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
im-online = { package = "srml-im-online", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
indices = { package = "srml-indices", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
membership = { package = "srml-membership", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
offences = { package = "srml-offences", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
prml-doughnut = { git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
randomness-collective-flip = { package = "srml-randomness-collective-flip", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
session = { package = "srml-session", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, features = ["historical"], branch = "chore/add-generic-asset-reward-method" }
staking = { package = "srml-staking", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
srml-staking-reward-curve = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "chore/add-generic-asset-reward-method" }
sudo = { package = "srml-sudo", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
support = { package = "srml-support", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
system = { package = "srml-system", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
system-rpc-runtime-api = { package = "srml-system-rpc-runtime-api", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
timestamp = { package = "srml-timestamp", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
treasury = { package = "srml-treasury", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
utility = { package = "srml-utility", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }
transaction-payment = { package = "srml-transaction-payment", git = "https://github.com/plugblockchain/plug-blockchain", default-features = false, branch = "chore/add-generic-asset-reward-method" }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4", git = "https://github.com/plugblockchain/plug-blockchain", branch = "chore/add-generic-asset-reward-method" }

[features]
default = ["std"]
std = [
	"authority-discovery-primitives/std",
	"authority-discovery/std",
	"authorship/std",
	"attestation/std",
	"babe-primitives/std",
	"babe/std",
	"client/std",
	"codec/std",
	"collective/std",
	"contracts/std",
	"contracts-rpc-runtime-api/std",
	"democracy/std",
	"elections-phragmen/std",
	"executive/std",
	"finality-tracker/std",
	"generic-asset/std",
	"grandpa/std",
	"im-online/std",
	"indices/std",
	"membership/std",
	"cennznet-primitives/std",
	"offchain-primitives/std",
	"offences/std",
	"primitives/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"rustc-hex",
	"safe-mix/std",
	"serde",
	"session/std",
	"sr-primitives/std",
	"sr-staking-primitives/std",
	"staking/std",
	"substrate-keyring",
	"substrate-session/std",
	"sudo/std",
	"support/std",
	"system/std",
	"system-rpc-runtime-api/std",
	"timestamp/std",
	"treasury/std",
	"utility/std",
	"transaction-payment/std",
	"version/std",
	"prml-doughnut/std",
	"cennzx-spot/std",
]
